FORMAT: 1A
HOST: localhost:8000

# apex

Apex is a simple top-down 2D shooter, inspired by the classic Boxhead series
and PlayerUnknown's Battlegrounds.

# Group State

## State [/game{?game_id,player_id}]
### Get current world state [GET]

Returns the current state of the game [game_id] from the perspective
of player [player_id]. Returns the all entities in a server-defined radius
around player.

+ Parameters
    + game_id (required, int) - The ID of the requested game.
    + player_id (required, int) - The ID of the requesting player.

+ Response 200 (application/json)

        [
            {
                "id"     : 912384,
                "name"   : "My Awesome Game
                "size"   : [5000.00, 10000.00],
                "radius" : 4000.00,
                "ammo": [
                    {
                        "gun"   : "Bazooka",
                        "count" : 5,
                        "pos"   : [1.06, 9.20],
                        "rad"   : 25.00
                    },
                    {
                        "gun"   : "Not-a-pistol",
                        "count" : 10,
                        "pos"   : [10.57, 3.19]
                        "rad"   : 100.00
                    }
                ]
                ,
                "bullets": [
                    {
                        "gun" : "lazer",
                        "rad" : 500.00,
                        "pos" : [12.73, 78.95]
                    }, 
                    {
                        "gun" : "pistol",
                        "rad" : 3000.00,
                        "pos" : [19.32, 21.77]
                    }
                ]
                ,
                "people": [
                    {
                        "id"   : "5023",
                        "name" : "AGao",
                        "hp"   : 5,
                        "pos"  : [0.00, 2.00],
                        "rad"  : 5.00,
                        "dir"  : "NW",
                        "inv"  : ["12301", "10123"]
                    },
                    {
                        "id"   : "5024",
                        "name" : "TBaig"
                        "hp"   : 100,
                        "pos"  : [300.55, 490.34],
                        "rad"  : 5.00,
                        "dir"  : "S",
                        "inv"  : []
                    }
                ]
                ,
                "guns": [
                    {
                        "id"    : "12301",
                        "type"  : "Pistol",
                        "ammo"  : 10000,
                        "owner" : "5023",
                        "pos"   : [0.00, 5.00],
                        "rad"   : 5.00
                    }
                    {
                        "id"    : "10123",
                        "type"  : "Not-a-pistol",
                        "ammo"  : 10,
                        "owner" : "5023",
                        "pos"   : [201.32, 321.55]
                        "rad"   : 5.00
                    },
                    {
                        "id"    : "1201",
                        "type"  : "Bazooka",
                        "ammo"  : 100,
                        "owner" : "",
                        "pos"   : [123.11, 321.11]
                        "rad"   : 5.00
                    },
                    {
                        "id"    : "9999",
                        "type"  : "Bazooka",
                        "ammo"  : 150,
                        "owner" : "",
                        "pos"   : [123.11, 321.11]
                        "rad"   : 5.00
                    },
                ]
                ,
                "rocks": [
                    {
                        "rad" : 3.45,
                        "pos" : [56.12, 33.12]
                    },
                    {
                        "rad" : 20.54,
                        "pos" : [52.32, 99.12]
                    }
                ]
            }
        ]


# Group Player

## Move [/move{?game_id,player_id}]
### Update location [POST]

+ Parameters
    + game_id   (required, int) - The ID of the game
    + player_id (required, int) - The ID of the current player

+ Request (application/json)

        [
            300.50, 
            900.99
        ]

+ Response 200

        Ok.
    
+ Response 400
    
        Bad request. Excessive movement detected.

## Shoot [/shoot{?game_id,player_id,gun_id}]
### Fire equipped weapon [GET]

+ Parameters
    + game_id   (required, int) - The ID of the game
    + player_id (required, int) - The ID of the current player
    + gun_id (required, int) - The ID of the gun being fired
        
+ Response 200

# Group Games

## List [/games]
### Retrieve all existing games [GET]
    
+ Response 200

        [ 
            {
                "game_name" : "My Game",
                "game_id"   : "12059",
                "game_players"   : ["player_name", "player_name2"]
            },
            {
                "game_name" : "Game 2",
                "game_id"   : "129083",
                "game_players"   : ["AGao", "TBaig"]
            }
        ]
            

## Create [/create]
### Make new game [POST]

+ Request (application/json)

        {
            "game_name"   : "new-game",
            "player_name" : "AGao"
        }
        
+ Response 200 (application/json)

        {
            "game_id"   : "My Game",
            "player_id" : "12301"
        }

## Join [/join{?game_id,player_name}]
### Enter existing game [GET]

+ Parameters
    + game_id (required, int) - The ID of the game to join
    + player_name (required, string) - The name of the current player

+ Response 200 (application/json)

        {
            "player_id" : "5483945"
        }