(* This module contains helper functions for generating items.
 * Guarantees unique IDs for all entities generated by the same
 * module instance. *)
type t

val create : unit -> t

val ammo : t -> Type.pos -> Type.name list -> Type.ammo

val bullet : t -> Type.player -> Type.gun -> Type.bullet list

val gun : t -> Type.pos -> Type.gun

val rock : t -> Type.pos -> Type.rock

(* Creates a player with the specified ID. *)

val player : t -> Type.pos -> Type.name -> Type.player
