(* This module contains helper functions for generating items.
 * Guarantees unique IDs for all entities generated by the same
 * module instance. *)
open Stype

type t

val create : unit -> t

val ammo : t -> pos -> name list -> ammo

val bullet : t -> player -> gun -> bullet list

val gun : t -> pos -> gun

val rock : t -> pos -> rock

(* Creates a player with the specified ID. *)

val player : t -> pos -> name -> player
